### ISSUE TITLE
post请求转发的时候客户端收到了分片，但是HttpObjectAggregator会卡住

### ISSUE THREAD

**Issue by zhuww0236** [ztgreat/proxy#2]
如题，用postman发post请求给proxy-server，HttpChannelHandler把FullHttpRequest分成两片：
httpRequestEncoder.encode(ctx, request, list);

客户端的ClientChannelHandler收到了两个分片，但是HttpObjectAggregator有时候会卡住，HttpReceiveHandler的channelRead没有被触发，导致请求卡住了。

这个大概是什么原因了

**Comment by zhuww0236** [comment]
断点发现是客户端收到了一个非法请求：
GET /\r\n
HttpRequestDecoder解析失败：
/bad-request
failure(java.lang.IllegalArgumentException: text is empty (possibly HTTP/0.9))
不知道这个请求是哪里触发的，然后HttpObjectAggregator就卡住了，再也解析不了请求了，关闭channel重新连接才能恢复。

**Comment by ztgreat** [comment]
> 如题，用postman发post请求给proxy-server，HttpChannelHandler把FullHttpRequest分成两片：
> httpRequestEncoder.encode(ctx, request, list);
> 
> 客户端的ClientChannelHandler收到了两个分片，但是HttpObjectAggregator有时候会卡住，HttpReceiveHandler的channelRead没有被触发，导致请求卡住了。
> 
> 这个大概是什么原因了

我这边简单测试了，没有问题啊，bad request 是你参数不对，业务服务器返回的
